workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - when: never

stages:
  - build
  - test

build:
  stage: build
  tags:
    - saas-linux-small-amd64
  image: maven:3.9.14-eclipse-temurin-21
  script:
    - mvn -B clean test package
  artifacts:
    paths:
      - ./target/*.jar

semgrep_sast:
  stage: test
  tags:
    - saas-linux-small-amd64
  image: semgrep/semgrep
  variables:
    SEMGREP_GITLAB_JSON: "1"
  script:
    - semgrep ci --code --gitlab-sast > gl-sast-report.json || true
  artifacts:
    when: always
    reports:
      sast: gl-sast-report.json

dependency_check_sca:
  stage: test
  tags:
    - saas-linux-small-amd64
  image: maven:3.9.14-eclipse-temurin-21
  script:
    - mvn -B -DskipTests dependency-check:check
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.html
