name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.14-eclipse-temurin-21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make mvnw executable
        if: ${{ hashFiles('mvnw') != '' }}
        run: chmod +x mvnw

      - name: Build, test, package
        run: mvn -B clean test package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: ./target/*.jar

  sast:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif || true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: semgrep.sarif
